// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA7n5s5Pd03W9S7rII8rnr0lSeoypjS9o',
    appId: '1:1023538609736:web:9bb92cc41707af1cd5627d',
    messagingSenderId: '1023538609736',
    projectId: 'fitness-node',
    authDomain: 'fitness-node.firebaseapp.com',
    storageBucket: 'fitness-node.firebasestorage.app',
    measurementId: 'G-BCV14S73SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbbxH22KcvfV817ouVDWUetlnPGr08pXU',
    appId: '1:1023538609736:android:4af537111b66dbd1d5627d',
    messagingSenderId: '1023538609736',
    projectId: 'fitness-node',
    storageBucket: 'fitness-node.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXxReqMWocYFPiU8WodGREz-i-q7-Uacs',
    appId: '1:1023538609736:ios:250130ed59f2b062d5627d',
    messagingSenderId: '1023538609736',
    projectId: 'fitness-node',
    storageBucket: 'fitness-node.firebasestorage.app',
    iosBundleId: 'com.example.fitnessManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXxReqMWocYFPiU8WodGREz-i-q7-Uacs',
    appId: '1:1023538609736:ios:250130ed59f2b062d5627d',
    messagingSenderId: '1023538609736',
    projectId: 'fitness-node',
    storageBucket: 'fitness-node.firebasestorage.app',
    iosBundleId: 'com.example.fitnessManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA7n5s5Pd03W9S7rII8rnr0lSeoypjS9o',
    appId: '1:1023538609736:web:366a37728b172b77d5627d',
    messagingSenderId: '1023538609736',
    projectId: 'fitness-node',
    authDomain: 'fitness-node.firebaseapp.com',
    storageBucket: 'fitness-node.firebasestorage.app',
    measurementId: 'G-VDSPWERPSH',
  );
}
